version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      armorcodehost: https://qa.armorcode.ai
      product: Product_1
      subProduct: Subproduct_1testttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt
      environment: Production
      token: 96830a4d-9fc7-4900-aeac-a14305e4e352
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
      end: 30
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              token=$ARMORCODE_TOKEN
              wget https://qa.armorcode.ai/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate