version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      armorcodehost: https://qa.armorcode.ai
      product: Aromorcode UI
      subProduct: Tushar-ArmorCode/90DaysOfDevOps
      environment: Production
      token: $ARMORCODE_TOKEN
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
      end: 30
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              token=bf871faa-412c-483b-a762-273449c6d758
              wget https://qa.armorcode.ai/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate